hbase:
  config:
    hbase.zookeeper.quorum: docker-hbase
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000


# 应用名称
spring:
  application:
    name: hbase
  # 应用服务 WEB 访问端口
server:
  port: 8080
